### PR TITLE
change order of avatar queries

### PR DESCRIPTION
**Pull request by petrus7**
add avatar image

### CODE REVIEW

**Comment by petrus7** [comment]
@giohappy yes it is. actually i think it should be ported there. The current implementation probably fails in DMZ zones. Grvatar is querying its server for default image. Please add a comment in the issue if it should be added to GeoNode official

**Comment by giohappy** [comment]
was avatar.providers.GravatarAvatarProvider already active in default GeoNode install?

**Comment by petrus7** [comment]
Yes it was. it is active by default and GeoNode is not changing this setting

**Comment by giohappy** [comment]
Ok so let's move this change upstream

Il ven 20 mar 2020, 17:10 Piotr Dankowski <notifications@github.com> ha
scritto:

**Pull request merged**
